In [1]:
print ("Hello World")

Hello World

In [2]:
import pandas

In [3]:
import pandas as pd 
from sklearn.datasets import fetch_openml

In [4]:
titanic = fetch_openml(name="titanic", as_frame=True, version=1)
data= pd.DataFrame(titanic.data)

data.head()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_arff_parser.py:200: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  frame = pd.concat(dfs, ignore_index=True)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
# 1. Check for missing values and handle them.
# 2. Check for duplicate rows and remove them.
# 3. Inspect the "Sex" column for inconsistencies and standardize values.
# 4. Detect and handle outliers in the "Age" and "Fare" columns.
# 5. Create a new "Family_Size" feature based on "SibSp" and "Parch".
# 6. Convert the "Embarked" column to numerical values using label encoding.
# 7. If a "Ticket_Purchase_Date" column existed, convert it to datetime and extract the year and month.
# 8. Clean the "Name" column by removing titles and converting to lowercase.
# 9. Bin the "Age" column into categories like 'Child', 'Teen', 'Adult', and 'Senior'.

In [6]:
import pandas as pd 
from sklearn.datasets import fetch_openml

titanic = fetch_openml(name="titanic", as_frame=True, version=1)    
data= pd.DataFrame(titanic.data)

data.head()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_arff_parser.py:200: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  frame = pd.concat(dfs, ignore_index=True)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"

In [7]:
missing_values = data.isnull().sum()
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
pclass          0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [8]:
duplicate_rows = data.duplicated().sum()
print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 0

In [9]:
rows_with_missing_values = data[data.isnull().any(axis=1)]
print("Rows with missing values:")
print(rows_with_missing_values)

Rows with missing values:
      pclass                                             name     sex  \
0        1.0                    Allen, Miss. Elisabeth Walton  female
1        1.0                   Allison, Master. Hudson Trevor    male
2        1.0                     Allison, Miss. Helen Loraine  female
3        1.0             Allison, Mr. Hudson Joshua Creighton    male
4        1.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female
...      ...                                              ...     ...
1304     3.0                             Zabour, Miss. Hileni  female
1305     3.0                            Zabour, Miss. Thamine  female
1306     3.0                        Zakarian, Mr. Mapriededer    male
1307     3.0                              Zakarian, Mr. Ortin    male
1308     3.0                               Zimmerman, Mr. Leo    male

          age  sibsp  parch  ticket      fare    cabin embarked  boat   body  \
0     29.0000    0.0    0.0   24160  211.3375       B5        S     2    NaN
1      0.9167    1.0    2.0  113781  151.5500  C22 C26        S    11    NaN
2      2.0000    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN
3     30.0000    1.0    2.0  113781  151.5500  C22 C26        S  None  135.0
4     25.0000    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN
...       ...    ...    ...     ...       ...      ...      ...   ...    ...
1304  14.5000    1.0    0.0    2665   14.4542     None        C  None  328.0
1305      NaN    1.0    0.0    2665   14.4542     None        C  None    NaN
1306  26.5000    0.0    0.0    2656    7.2250     None        C  None  304.0
1307  27.0000    0.0    0.0    2670    7.2250     None        C  None    NaN
1308  29.0000    0.0    0.0  315082    7.8750     None        S  None    NaN

                            home.dest
0                        St Louis, MO
1     Montreal, PQ / Chesterville, ON
2     Montreal, PQ / Chesterville, ON
3     Montreal, PQ / Chesterville, ON
4     Montreal, PQ / Chesterville, ON
...                               ...
1304                             None
1305                             None
1306                             None
1307                             None
1308                             None

[1309 rows x 13 columns]

In [10]:
data['sex'].isna().sum()

0

In [11]:
inspect_column_sex= data['sex'].isna().sum()  
print("Missing values in the 'sex' column:", inspect_column_sex)

Missing values in the 'sex' column: 0

In [12]:
inspect_column_sex_unique= data['sex'].unique()
print("Unique values in the 'sex' column:", inspect_column_sex_unique)

Unique values in the 'sex' column: ['female', 'male']
Categories (2, object): ['female', 'male']

In [13]:
rows_with_missing_value_age = data[data['age'].isnull()]
print("Rows with missing values in the 'age' column:")
print(rows_with_missing_value_age)

Rows with missing values in the 'age' column:
      pclass                                               name     sex  age  \
15       1.0                                Baumann, Mr. John D    male  NaN
37       1.0      Bradley, Mr. George ('George Arthur Brayton')    male  NaN
40       1.0                          Brewe, Dr. Arthur Jackson    male  NaN
46       1.0                              Cairns, Mr. Alexander    male  NaN
59       1.0  Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...  female  NaN
...      ...                                                ...     ...  ...
1293     3.0                  Williams, Mr. Howard Hugh 'Harry'    male  NaN
1297     3.0                             Wiseman, Mr. Phillippe    male  NaN
1302     3.0                                  Yousif, Mr. Wazli    male  NaN
1303     3.0                              Yousseff, Mr. Gerious    male  NaN
1305     3.0                              Zabour, Miss. Thamine  female  NaN

      sibsp  parch      ticket     fare cabin embarked  boat  body  \
15      0.0    0.0    PC 17318  25.9250  None        S  None   NaN
37      0.0    0.0      111427  26.5500  None        S     9   NaN
40      0.0    0.0      112379  39.6000  None        C  None   NaN
46      0.0    0.0      113798  31.0000  None        S  None   NaN
59      0.0    0.0       17770  27.7208  None        C     5   NaN
...     ...    ...         ...      ...   ...      ...   ...   ...
1293    0.0    0.0    A/5 2466   8.0500  None        S  None   NaN
1297    0.0    0.0  A/4. 34244   7.2500  None        S  None   NaN
1302    0.0    0.0        2647   7.2250  None        C  None   NaN
1303    0.0    0.0        2627  14.4583  None        C  None   NaN
1305    1.0    0.0        2665  14.4542  None        C  None   NaN

             home.dest
15        New York, NY
37     Los Angeles, CA
40    Philadelphia, PA
46                None
59        New York, NY
...                ...
1293              None
1297              None
1302              None
1303              None
1305              None

[263 rows x 13 columns]

In [14]:
inspect_column_fare_unique= data['fare'].unique()
print("Unique values in the 'fare' column:", inspect_column_fare_unique)

Unique values in the 'fare' column: [211.3375 151.55    26.55    77.9583   0.      51.4792  49.5042 227.525
  69.3     78.85    30.      25.925  247.5208  76.2917  75.2417  52.5542
 221.7792  26.      91.0792 135.6333  35.5     31.     164.8667 262.375
  55.      30.5     50.4958  39.6     27.7208 134.5     26.2875  27.4458
 512.3292   5.      47.1    120.      61.175   53.1     86.5     29.7
 136.7792  52.      25.5875  83.1583  25.7     71.      71.2833  57.
  81.8583 106.425   56.9292  78.2667  31.6792  31.6833 110.8833  26.3875
  27.75   263.     133.65    49.5     79.2     38.5    211.5     59.4
  89.1042  34.6542  28.5    153.4625  63.3583  55.4417  76.7292  42.4
  83.475   93.5     42.5     51.8625  50.      57.9792  90.      30.6958
  80.      28.7125  25.9292  39.4     45.5    146.5208  82.1708  57.75
 113.275   26.2833 108.9     25.7417  61.9792  66.6     40.125   55.9
  60.      82.2667  32.3208  79.65    28.5375  33.5     34.0208  75.25
  77.2875  61.3792  35.      24.      13.      11.5     10.5     12.525
  39.      29.      21.      13.5     26.25    36.75    73.5     31.5
  23.      32.5     13.8583  14.5     33.      65.      16.      12.275
  27.      15.      13.7917  12.35    10.7083  41.5792  12.      12.875
  15.0458  37.0042  15.5792  19.5     14.       9.6875  30.0708  13.8625
  15.05    12.7375  15.0333  18.75    12.65    15.75     7.55    20.25
   7.65     7.925    7.2292   7.25     8.05     9.475    9.35    18.7875
   7.8875   7.05     8.3     22.525    7.8542  31.275    7.775    7.7958
   7.8958  17.8     31.3875   7.225   14.4583  15.85    19.2583  14.4542
   7.8792   4.0125  56.4958   7.75    15.2458  15.5     16.1      7.725
   7.0458   7.2833   7.8208   6.75     8.6625   7.7333   7.4958   7.6292
  15.9      8.1583  10.5167  10.1708   6.95    14.4     24.15    17.4
   9.5     20.575   12.475   13.9      6.975   15.1     34.375    7.7417
  20.525    7.85    46.9      8.3625   9.8458   8.85    19.9667  14.1083
   6.8583   8.9625  12.2875   6.45     7.0542   8.1125   6.4958   8.6542
  11.1333  23.45     9.825    7.125    8.4333   7.5208  13.4167   7.8292
   7.7375  22.025   12.1833   9.5875   9.4833  25.4667   6.4375  15.55
   7.5792   7.1417  23.25     7.7875   8.0292   8.4583  15.7417  11.2417
   7.8      6.2375   9.225    3.1708   8.4042   7.3125   9.2167   8.6833
  21.075   39.6875   8.7125  13.775    7.      22.3583   8.1375  29.125
   7.7208  20.2125   7.7292   7.575   69.55     9.325   21.6792  16.7
   7.7792  27.9         nan   9.8375  10.4625   8.5167   9.8417   9.
  18.       7.875 ]

In [15]:
outliers_age = data['age'].describe()
outliers_fare = data['fare'].describe()
print("Outliers in the 'age' column:")
print(outliers_age)
print("Outliers in the 'fare' column:")
print(outliers_fare)

Outliers in the 'age' column:
count    1046.000000
mean       29.881135
std        14.413500
min         0.166700
25%        21.000000
50%        28.000000
75%        39.000000
max        80.000000
Name: age, dtype: float64
Outliers in the 'fare' column:
count    1308.000000
mean       33.295479
std        51.758668
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: fare, dtype: float64

In [16]:
data['FamilySize'] = data['sibsp'] + data['parch'] + 1
print("Family Size distribution:")
print(data['FamilySize'].value_counts())

Family Size distribution:
FamilySize
1.0     790
2.0     235
3.0     159
4.0      43
6.0      25
5.0      22
7.0      16
11.0     11
8.0       8
Name: count, dtype: int64

In [20]:
print(data.head())

   pclass                                             name     sex      age  \
0     1.0                    Allen, Miss. Elisabeth Walton  female  29.0000
1     1.0                   Allison, Master. Hudson Trevor    male   0.9167
2     1.0                     Allison, Miss. Helen Loraine  female   2.0000
3     1.0             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4     1.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

   sibsp  parch  ticket      fare    cabin embarked  boat   body  \
0    0.0    0.0   24160  211.3375       B5        S     2    NaN
1    1.0    2.0  113781  151.5500  C22 C26        S    11    NaN
2    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN
3    1.0    2.0  113781  151.5500  C22 C26        S  None  135.0
4    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN

                         home.dest  FamilySize
0                     St Louis, MO         1.0
1  Montreal, PQ / Chesterville, ON         4.0
2  Montreal, PQ / Chesterville, ON         4.0
3  Montreal, PQ / Chesterville, ON         4.0
4  Montreal, PQ / Chesterville, ON         4.0

In [21]:
print(data['embarked'].head())

0    S
1    S
2    S
3    S
4    S
Name: embarked, dtype: category
Categories (3, object): ['C', 'Q', 'S']

TypeError: Cannot setitem on a Categorical with a new category (Unknown), set the categories first

In [23]:
from sklearn.datasets import fetch_openml

titanic = fetch_openml(name="titanic", as_frame=True, version=1)    
data= pd.DataFrame(titanic.data)

data.head()

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\datasets\_arff_parser.py:200: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  frame = pd.concat(dfs, ignore_index=True)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,None,NaN,"Montreal, PQ / Chesterville, ON"

In [25]:
embarked_str = data['embarked'].astype(str).fillna('Unknown')
codes, uniques = pd.factorize(embarked_str)
data['embarked_encoded'] = codes    
print("Unique values in embarked column:")
print(uniques)
print(data[['embarked', 'embarked_encoded']].head())

Unique values in embarked column:
Index(['S', 'C', 'nan', 'Q'], dtype='object')
  embarked  embarked_encoded
0        S                 0
1        S                 0
2        S                 0
3        S                 0
4        S                 0

In [26]:
print(data.head())

   pclass                                             name     sex      age  \
0     1.0                    Allen, Miss. Elisabeth Walton  female  29.0000
1     1.0                   Allison, Master. Hudson Trevor    male   0.9167
2     1.0                     Allison, Miss. Helen Loraine  female   2.0000
3     1.0             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4     1.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

   sibsp  parch  ticket      fare    cabin embarked  boat   body  \
0    0.0    0.0   24160  211.3375       B5        S     2    NaN
1    1.0    2.0  113781  151.5500  C22 C26        S    11    NaN
2    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN
3    1.0    2.0  113781  151.5500  C22 C26        S  None  135.0
4    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN

                         home.dest  embarked_encoded
0                     St Louis, MO                 0
1  Montreal, PQ / Chesterville, ON                 0
2  Montreal, PQ / Chesterville, ON                 0
3  Montreal, PQ / Chesterville, ON                 0
4  Montreal, PQ / Chesterville, ON                 0

In [28]:
import numpy as np
from datetime import datetime, timedelta
# Number of rows
n_rows = len(data)

# Define start and end dates as datetime objects
start_date = datetime(2021, 1,1)
end_date = datetime(2026, 6, 30)

# Total number of days between start and end
delta_days = (end_date - start_date).days

# Generate random offsets (in days) for each row
random_days = np.random.randint(0, delta_days + 1, size=n_rows)

# Compute the random dates
random_datetimes = [start_date + timedelta(days=int(d)) for d in random_days]

In [29]:
data['Ticket_Purchase_Date'] = [
    dt.strftime('%d-%m-%Y') for dt in random_datetimes
]

In [30]:
data[['Ticket_Purchase_Date']].head()

  Ticket_Purchase_Date
0           25-01-2024
1           01-01-2024
2           01-05-2024
3           21-05-2022
4           11-07-2025

In [32]:
# Convert to datetime (pandas)
data['Ticket_Purchase_Date_dt'] = pd.to_datetime(
    data['Ticket_Purchase_Date'],
    format='%d-%m-%Y'
)

# Extract year and month as new features
data['Ticket_Purchase_Year'] = data['Ticket_Purchase_Date_dt'].dt.year
data['Ticket_Purchase_Month'] = data['Ticket_Purchase_Date_dt'].dt.month

In [33]:
data[['Ticket_Purchase_Date',
      'Ticket_Purchase_Date_dt',
      'Ticket_Purchase_Year',
      'Ticket_Purchase_Month']].head()

,Ticket_Purchase_Date,Ticket_Purchase_Date_dt,Ticket_Purchase_Year,Ticket_Purchase_Month
0,25-01-2024,2024-01-25,2024,1
1,01-01-2024,2024-01-01,2024,1
2,01-05-2024,2024-05-01,2024,5
3,21-05-2022,2022-05-21,2022,5
4,11-07-2025,2025-07-11,2025,7

In [39]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def add_random_purchase_date(
    df,
    start='2024-01-01',
    end='2026-06-30',
    date_col='Ticket_Purchase_Date',
    datetime_col='Ticket_Purchase_Date_dt',
    year_col='Ticket_Purchase_Year',
    month_col='Ticket_Purchase_Month'
):
    """
    Adds random ticket purchase dates and derived year/month columns to df.

    - start, end: strings 'YYYY-MM-DD' defining the date range.
    - date_col: name of the string date column (DD-MM-YYYY).
    - datetime_col: name of the pandas datetime column.
    - year_col, month_col: names for extracted year and month.
    """

    # 1. Convert start/end to datetime
    start_dt = datetime.strptime(start, '%Y-%m-%d')
    end_dt = datetime.strptime(end, '%Y-%m-%d')

    # 2. Compute the range in days
    delta_days = (end_dt - start_dt).days

    # 3. Generate random day offsets
    n_rows = len(df)
    random_days = np.random.randint(0, delta_days + 1, size=n_rows)

    # 4. Build random datetime values
    random_datetimes = [start_dt + timedelta(days=int(d)) for d in random_days]

    # 5. Store as DD-MM-YYYY strings
    df[date_col] = [dt.strftime('%d-%m-%Y') for dt in random_datetimes]

    # 6. Convert to pandas datetime
    df[datetime_col] = pd.to_datetime(df[date_col], format='%d-%m-%Y')

    # 7. Extract year and month
    df[year_col] = df[datetime_col].dt.year
    df[month_col] = df[datetime_col].dt.month

    return df

In [37]:
data = add_random_purchase_date(
    data,
    start='2024-01-01',
    end='2026-06-30',
    date_col='PurchaseDate',
    datetime_col='PurchaseDate_dt',
    year_col='PurchaseYear',
    month_col='PurchaseMonth'
)

In [38]:
data.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,...,home.dest,embarked_encoded,Ticket_Purchase_Date,Ticket_Purchase_Date_dt,Ticket_Purchase_Year,Ticket_Purchase_Month,PurchaseDate,PurchaseDate_dt,PurchaseYear,PurchaseMonth
0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,...,"St Louis, MO",0,25-01-2024,2024-01-25,2024,1,18-02-2026,2026-02-18,2026,2
1,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,...,"Montreal, PQ / Chesterville, ON",0,01-01-2024,2024-01-01,2024,1,20-12-2024,2024-12-20,2024,12
2,1.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,...,"Montreal, PQ / Chesterville, ON",0,01-05-2024,2024-05-01,2024,5,06-07-2024,2024-07-06,2024,7
3,1.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,...,"Montreal, PQ / Chesterville, ON",0,21-05-2022,2022-05-21,2022,5,19-12-2024,2024-12-19,2024,12
4,1.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,...,"Montreal, PQ / Chesterville, ON",0,11-07-2025,2025-07-11,2025,7,14-12-2024,2024-12-14,2024,12

In [40]:
import re
import pandas as pd

def clean_name_column(df, name_col='name', new_col='name_clean'):
    """
    Clean a Titanic-style Name column by:
    - Removing common titles (Mr, Mrs, Miss, Ms, Master, Dr, etc.)
    - Converting to lowercase
    - Stripping extra whitespace

    df:       pandas DataFrame
    name_col: column name with raw names
    new_col:  column name to store cleaned names
    """

    # Work on a string view to be safe
    names = df[name_col].astype(str)

    # 1. Define common titles in a regex pattern
    titles_pattern = r'\b(Mr|Mrs|Miss|Ms|Master|Dr|Rev|Col|Major|Capt|Lady|Sir|Mlle|Mme|Countess)\.?'

    # 2. Remove titles using regex
    #    - re.IGNORECASE handles upper/lower/mixed case
    names_no_titles = names.apply(
        lambda x: re.sub(titles_pattern, '', x, flags=re.IGNORECASE)
    )

    # 3. Remove extra spaces and commas around the remaining name
    names_cleaned = names_no_titles.str.replace(',', ' ', regex=False)
    names_cleaned = names_cleaned.str.replace('\s+', ' ', regex=True)  # collapse multiple spaces
    names_cleaned = names_cleaned.str.strip()

    # 4. Convert to lowercase
    df[new_col] = names_cleaned.str.lower()

    return df

In [42]:
print(data['name'].head())

0                      Allen, Miss. Elisabeth Walton
1                     Allison, Master. Hudson Trevor
2                       Allison, Miss. Helen Loraine
3               Allison, Mr. Hudson Joshua Creighton
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
Name: name, dtype: object

In [44]:
print(data.columns)

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'boat', 'body', 'home.dest', 'embarked_encoded',
       'Ticket_Purchase_Date', 'Ticket_Purchase_Date_dt',
       'Ticket_Purchase_Year', 'Ticket_Purchase_Month', 'PurchaseDate',
       'PurchaseDate_dt', 'PurchaseYear', 'PurchaseMonth'],
      dtype='object')

In [43]:
# If the column name is 'Name' (capital N), pass that explicitly
data = clean_name_column(data, name_col='Name', new_col='name_clean')

# Inspect a few results
data[['Name', 'name_clean']].head()

KeyError: 'Name'

In [45]:
import re
import pandas as pd

def clean_name_column(df, name_col='name', new_col='name_clean'):
    """
    Clean a Titanic-style Name column by:
    - Removing common titles (Mr, Mrs, Miss, Ms, Master, Dr, etc.)
    - Converting to lowercase
    - Stripping extra whitespace

    df:       pandas DataFrame
    name_col: column name with raw names
    new_col:  column name to store cleaned names
    """

    # Work on a string view to be safe
    names = df[name_col].astype(str)

    # 1. Define common titles in a regex pattern
    titles_pattern = r'\b(Mr|Mrs|Miss|Ms|Master|Dr|Rev|Col|Major|Capt|Lady|Sir|Mlle|Mme|Countess)\.?'

    # 2. Remove titles using regex
    names_no_titles = names.apply(
        lambda x: re.sub(titles_pattern, '', x, flags=re.IGNORECASE)
    )

    # 3. Remove extra spaces and commas
    names_cleaned = names_no_titles.str.replace(',', ' ', regex=False)
    names_cleaned = names_cleaned.str.replace(r'\s+', ' ', regex=True)  # collapse multiple spaces
    names_cleaned = names_cleaned.str.strip()

    # 4. Convert to lowercase and save as new column
    df[new_col] = names_cleaned.str.lower()

    return df

In [46]:
data = clean_name_column(data, name_col='name', new_col='name_clean')
print(data[['name', 'name_clean']].head())
data[['name', 'name_clean']].head()

                                              name  \
0                    Allen, Miss. Elisabeth Walton
1                   Allison, Master. Hudson Trevor
2                     Allison, Miss. Helen Loraine
3             Allison, Mr. Hudson Joshua Creighton
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)

                                     name_clean
0                        allen elisabeth walton
1                         allison hudson trevor
2                         allison helen loraine
3               allison hudson joshua creighton
4  allison s. hudson j c (bessie waldo daniels)

,name,name_clean
0,"Allen, Miss. Elisabeth Walton",allen elisabeth walton
1,"Allison, Master. Hudson Trevor",allison hudson trevor
2,"Allison, Miss. Helen Loraine",allison helen loraine
3,"Allison, Mr. Hudson Joshua Creighton",allison hudson joshua creighton
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",allison s. hudson j c (bessie waldo daniels)

In [47]:
print(data.head())

   pclass                                             name     sex      age  \
0     1.0                    Allen, Miss. Elisabeth Walton  female  29.0000
1     1.0                   Allison, Master. Hudson Trevor    male   0.9167
2     1.0                     Allison, Miss. Helen Loraine  female   2.0000
3     1.0             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4     1.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

   sibsp  parch  ticket      fare    cabin embarked  ... embarked_encoded  \
0    0.0    0.0   24160  211.3375       B5        S  ...                0
1    1.0    2.0  113781  151.5500  C22 C26        S  ...                0
2    1.0    2.0  113781  151.5500  C22 C26        S  ...                0
3    1.0    2.0  113781  151.5500  C22 C26        S  ...                0
4    1.0    2.0  113781  151.5500  C22 C26        S  ...                0

   Ticket_Purchase_Date Ticket_Purchase_Date_dt  Ticket_Purchase_Year  \
0            25-01-2024              2024-01-25                  2024
1            01-01-2024              2024-01-01                  2024
2            01-05-2024              2024-05-01                  2024
3            21-05-2022              2022-05-21                  2022
4            11-07-2025              2025-07-11                  2025

  Ticket_Purchase_Month PurchaseDate  PurchaseDate_dt  PurchaseYear  \
0                     1   18-02-2026       2026-02-18          2026
1                     1   20-12-2024       2024-12-20          2024
2                     5   06-07-2024       2024-07-06          2024
3                     5   19-12-2024       2024-12-19          2024
4                     7   14-12-2024       2024-12-14          2024

  PurchaseMonth                                    name_clean
0             2                        allen elisabeth walton
1            12                         allison hudson trevor
2             7                         allison helen loraine
3            12               allison hudson joshua creighton
4            12  allison s. hudson j c (bessie waldo daniels)

[5 rows x 23 columns]

   pclass                                             name     sex      age  \
0     1.0                    Allen, Miss. Elisabeth Walton  female  29.0000
1     1.0                   Allison, Master. Hudson Trevor    male   0.9167
2     1.0                     Allison, Miss. Helen Loraine  female   2.0000
3     1.0             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4     1.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

   sibsp  parch  ticket      fare    cabin embarked  boat   body  \
0    0.0    0.0   24160  211.3375       B5        S     2    NaN
1    1.0    2.0  113781  151.5500  C22 C26        S    11    NaN
2    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN
3    1.0    2.0  113781  151.5500  C22 C26        S  None  135.0
4    1.0    2.0  113781  151.5500  C22 C26        S  None    NaN

                         home.dest  embarked_encoded Ticket_Purchase_Date  \
0                     St Louis, MO                 0           25-01-2024
1  Montreal, PQ / Chesterville, ON                 0           01-01-2024
2  Montreal, PQ / Chesterville, ON                 0           01-05-2024
3  Montreal, PQ / Chesterville, ON                 0           21-05-2022
4  Montreal, PQ / Chesterville, ON                 0           11-07-2025

  Ticket_Purchase_Date_dt  Ticket_Purchase_Year  Ticket_Purchase_Month  \
0              2024-01-25                  2024                      1
1              2024-01-01                  2024                      1
2              2024-05-01                  2024                      5
3              2022-05-21                  2022                      5
4              2025-07-11                  2025                      7

  PurchaseDate_dt                                    name_clean
0      2026-02-18                        allen elisabeth walton
1      2024-12-20                         allison hudson trevor
2      2024-07-06                         allison helen loraine
3      2024-12-19               allison hudson joshua creighton
4      2024-12-14  allison s. hudson j c (bessie waldo daniels)

In [ ]:
data = data.drop(columns=['PurchaseDate', 'PurchaseMonth', 'PurchaseYear'])
print(data.head())